
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundry;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Aas1
 */
public class form_cucian extends javax.swing.JFrame {
    private Connection con;
    private Statement stat;
    private ResultSet res;
    private String t;
    
    private void koneksi(){
    try {
    Class.forName("com.mysql.jdbc.Driver");
    con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/laundry","root","");
    stat=(Statement) con.createStatement();
    } catch (ClassNotFoundException | SQLException e) {
    JOptionPane.showMessageDialog(null, e);
    }
    }
    
    private void kosongkan()
        {
        txt_id_cucian.setText("");
        txt_nama_cucian.setText(""); 
        txt_satuan.setText("");
        txt_harga.setText("");
        txt_nama_cucian.requestFocus();
         } 
    /**
     * Creates new form FrDataAkun
     */
    public form_cucian() {
        initComponents();
        txt_id_cucian.setVisible(false);
        setTitle("Data Cucian");
        koneksi();
        tabel();
        kosongkan();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
        (screenSize.width - frameSize.width) / 2,
        (screenSize.height - frameSize.height) / 2);
    }
    
    private void tabel(){ 
        DefaultTableModel t= new DefaultTableModel();
         t.addColumn("Nama Cucian"); 
         t.addColumn("Satuan"); 
         t.addColumn("Harga");
         jTable1.setModel(t); 
         try{ 
         res=stat.executeQuery("select * from jenis_cucian"); 
         while (res.next()) { 
         t.addRow(new Object[]{ res.getString("nama_cucian"),
         res.getString("satuan"), 
         res.getString("biaya_cucian") 
         }); 
         }
         }catch (Exception e) { 
         JOptionPane.showMessageDialog(rootPane, e); 
         }
    }
    
        private void nonaktif()
    {
        txt_satuan.setEnabled(false);
        txt_harga.setEnabled(false);
        btsimpan.setEnabled(false);
        btubah.setEnabled(false);
        bthapus.setEnabled(false);
        btbatal.setEnabled(false);
    }
    
    private void aktif(){
          txt_satuan.setEnabled(true);
          txt_harga.setEnabled(true);
          btsimpan.setEnabled(true);
          btubah.setEnabled(true);
          bthapus.setEnabled(true);
          btbatal.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_nama_cucian = new javax.swing.JTextField();
        txt_id_cucian = new javax.swing.JTextField();
        txt_satuan = new javax.swing.JTextField();
        txt_harga = new javax.swing.JTextField();
        bttambah = new javax.swing.JButton();
        btcari = new javax.swing.JButton();
        btsimpan = new javax.swing.JButton();
        btubah = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btbatal = new javax.swing.JButton();
        btkembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nama_cucian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nama_cucianKeyPressed(evt);
            }
        });
        getContentPane().add(txt_nama_cucian, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 190, 30));

        txt_id_cucian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_cucianActionPerformed(evt);
            }
        });
        getContentPane().add(txt_id_cucian, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 88, -1));
        getContentPane().add(txt_satuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 190, 30));

        txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 191, 30));

        bttambah.setBackground(new java.awt.Color(204, 204, 255));
        bttambah.setText("Tambah");
        bttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttambahActionPerformed(evt);
            }
        });
        getContentPane().add(bttambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 98, 35));

        btcari.setBackground(new java.awt.Color(204, 204, 255));
        btcari.setText("Cari");
        btcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcariActionPerformed(evt);
            }
        });
        getContentPane().add(btcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 100, 35));

        btsimpan.setBackground(new java.awt.Color(204, 204, 255));
        btsimpan.setText("Simpan");
        btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 100, 35));

        btubah.setBackground(new java.awt.Color(204, 204, 255));
        btubah.setText("Ubah");
        btubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btubahActionPerformed(evt);
            }
        });
        getContentPane().add(btubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 100, 35));

        bthapus.setBackground(new java.awt.Color(204, 204, 255));
        bthapus.setText("Hapus");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });
        getContentPane().add(bthapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 100, 35));

        btbatal.setBackground(new java.awt.Color(204, 204, 255));
        btbatal.setText("Batal");
        btbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbatalActionPerformed(evt);
            }
        });
        getContentPane().add(btbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 100, 35));

        btkembali.setBackground(new java.awt.Color(204, 204, 255));
        btkembali.setText("Kembali");
        btkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 80, 33));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 440, 131));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/2.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nama_cucianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nama_cucianKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nama_cucianKeyPressed

    private void btcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcariActionPerformed
        // TODO add your handling code here:
         aktif();
        try { 
        res=stat.executeQuery("select * from jenis_cucian where "+ "nama_cucian='" +txt_nama_cucian.getText()
        +"'" );
        while (res.next()) 
        {
            txt_id_cucian.setText(res.getString("id_cucian"));
            txt_nama_cucian.setText(res.getString("nama_cucian")); 
            txt_satuan.setText(res.getString("satuan"));
            txt_harga.setText(res.getString("biaya_cucian"));
        }                                        
         }       
        catch (Exception e) { 
        JOptionPane.showMessageDialog(rootPane, e); 
}
    }//GEN-LAST:event_btcariActionPerformed

    private void btsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsimpanActionPerformed
        // TODO add your handling code here:
         aktif();
        
        try {
        stat.executeUpdate("insert into jenis_cucian values (NULL," 
       + "'" + txt_nama_cucian.getText()+"',"
       + "'" + txt_satuan.getText()+"',"
       + "'" + txt_harga.getText()+"')");
       JOptionPane.showMessageDialog(null, "Berhasil Menyimpan Data"); 
       } catch (SQLException | HeadlessException e) { 
       JOptionPane.showMessageDialog(null, "Perintah Salah : "+e);
       }finally{
                tabel();
                kosongkan();
        } 
    }//GEN-LAST:event_btsimpanActionPerformed

    private void btubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btubahActionPerformed
        // TODO add your handling code here:
        try {
            stat.executeUpdate("update jenis_cucian set "
                + "nama_cucian='"+txt_nama_cucian.getText()+"',"
                + "satuan='"+txt_satuan.getText()+"',"
                + "biaya_cucian='"+txt_harga.getText()+"'"

                + " where " + "id_cucian='"+txt_id_cucian.getText()+"'" );
            
            JOptionPane.showMessageDialog(rootPane, "Data berhasil Diubah");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }finally{
         tabel();
         kosongkan();
        }
    }//GEN-LAST:event_btubahActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        // TODO add your handling code here:
        try { 
            stat.executeUpdate("delete from jenis_cucian where " 
            + "nama_cucian='"+txt_nama_cucian.getText()
            +"'" ); 
            kosongkan(); 
            JOptionPane.showMessageDialog(null, "Berhasil");
             } catch (Exception e) { 
            JOptionPane.showMessageDialog(null, "pesan salah : "+e);
             }finally{
                     tabel();
          }
    }//GEN-LAST:event_bthapusActionPerformed

    private void btbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbatalActionPerformed
        // TODO add your handling code here:
        kosongkan();
        nonaktif();
    }//GEN-LAST:event_btbatalActionPerformed

    private void btkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkembaliActionPerformed
        // TODO add your handling code here:
        new form_utama().setVisible(true);
        dispose();
    }//GEN-LAST:event_btkembaliActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        if (i == -1){
            return;
        }        
        String nama_cucian = (String) jTable1.getValueAt(i,0);
        txt_nama_cucian.setText(nama_cucian);
        String satuan = (String) jTable1.getValueAt(i,1);
        txt_satuan.setText(satuan);
        String harga = (String) jTable1.getValueAt(i,2);
        txt_harga.setText(harga); 
        
    try { 
        res=stat.executeQuery("select * from jenis_cucian where "+ "nama_cucian='" +txt_nama_cucian.getText()
        +"'" );
        while (res.next()) 
        {
            txt_id_cucian.setText(res.getString("id_cucian"));
        }                                        
         }       
        catch (Exception e) { 
        JOptionPane.showMessageDialog(rootPane, e); 
}    
        
        
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        nonaktif();
        tabel();
    }//GEN-LAST:event_formWindowActivated

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
        // TODO add your handling code here:
        aktif();
        kosongkan();
    }//GEN-LAST:event_bttambahActionPerformed

    private void txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaActionPerformed

    private void txt_id_cucianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_cucianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_cucianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_cucian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_cucian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_cucian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_cucian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_cucian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbatal;
    private javax.swing.JButton btcari;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btkembali;
    private javax.swing.JButton btsimpan;
    private javax.swing.JButton bttambah;
    private javax.swing.JButton btubah;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_id_cucian;
    private javax.swing.JTextField txt_nama_cucian;
    private javax.swing.JTextField txt_satuan;
    // End of variables declaration//GEN-END:variables
}
