/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundry;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Aas1
 */
public class form_user extends javax.swing.JFrame {
    private Connection con;
    private Statement stat;
    private ResultSet res;
    private String t;
    
    private void koneksi(){
    try {
    Class.forName("com.mysql.jdbc.Driver");
    con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/laundry","root","");
    stat=(Statement) con.createStatement();
    } catch (ClassNotFoundException | SQLException e) {
    JOptionPane.showMessageDialog(null, e);
    }
    }
    
    private void kosongkan()
        { 
        user.setText(""); 
        pass.setText("");
        nama.setText("");
        cmhak.setSelectedItem("");
        user.requestFocus();
         } 
    
    private void nonaktif()
    {
        pass.setEnabled(false);
        nama.setEnabled(false);
        cmhak.setEnabled(false);
        btsimpan.setEnabled(false);
        btubah.setEnabled(false);
        bthapus.setEnabled(false);
        btbatal.setEnabled(false);
    }
    
    private void aktif(){
         pass.setEnabled(true);
        nama.setEnabled(true);
        cmhak.setEnabled(true);
        btsimpan.setEnabled(true);
        btubah.setEnabled(true);
        bthapus.setEnabled(true);
        btbatal.setEnabled(true);
    }
    /**
     * Creates new form form_user
     */
    public form_user() {
        initComponents();
        setTitle("Data User");
        koneksi();
        tabel();
        kosongkan();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
        (screenSize.width - frameSize.width) / 2,
        (screenSize.height - frameSize.height) / 2);
    }
    
    private void tabel(){ 
        DefaultTableModel t= new DefaultTableModel();
         t.addColumn("Username"); 
         t.addColumn("Nama User"); 
         t.addColumn("Password");
         t.addColumn("level");
         jTable1.setModel(t); 
         try{ 
         res=stat.executeQuery("select * from user"); 
         while (res.next()) { 
         t.addRow(new Object[]{ res.getString("username"),
         res.getString("nama_user"),
         res.getString("password"), 
         res.getString("level") 
         }); 
         }
         }catch (Exception e) { 
         JOptionPane.showMessageDialog(rootPane, e); 
         }
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        user = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        cmhak = new javax.swing.JComboBox<>();
        bttambah = new javax.swing.JButton();
        btcari = new javax.swing.JButton();
        btsimpan = new javax.swing.JButton();
        btubah = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btbatal = new javax.swing.JButton();
        tbkembali = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 450, 140));

        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userKeyPressed(evt);
            }
        });
        jPanel5.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 260, 30));

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel5.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 260, 30));
        jPanel5.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 260, 30));

        cmhak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Admin", "Kasir" }));
        jPanel5.add(cmhak, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 260, 30));

        bttambah.setBackground(new java.awt.Color(204, 204, 255));
        bttambah.setText("Tambah");
        bttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttambahActionPerformed(evt);
            }
        });
        jPanel5.add(bttambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 80, 40));

        btcari.setBackground(new java.awt.Color(204, 204, 255));
        btcari.setText("Cari");
        btcari.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcariActionPerformed(evt);
            }
        });
        jPanel5.add(btcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 80, 40));

        btsimpan.setBackground(new java.awt.Color(204, 204, 255));
        btsimpan.setText("Simpan");
        btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsimpanActionPerformed(evt);
            }
        });
        jPanel5.add(btsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 82, 33));

        btubah.setBackground(new java.awt.Color(204, 204, 255));
        btubah.setText("Ubah");
        btubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btubahActionPerformed(evt);
            }
        });
        jPanel5.add(btubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 82, 33));

        bthapus.setBackground(new java.awt.Color(204, 204, 255));
        bthapus.setText("Hapus");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });
        jPanel5.add(bthapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 81, 35));

        btbatal.setBackground(new java.awt.Color(204, 204, 255));
        btbatal.setText("Batal");
        btbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbatalActionPerformed(evt);
            }
        });
        jPanel5.add(btbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 81, 36));

        tbkembali.setBackground(new java.awt.Color(204, 204, 255));
        tbkembali.setText("Kembali");
        tbkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbkembaliActionPerformed(evt);
            }
        });
        jPanel5.add(tbkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 81, 42));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/4.png"))); // NOI18N
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        nonaktif();
        tabel();
    }//GEN-LAST:event_formWindowActivated

    private void tbkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbkembaliActionPerformed
        // TODO add your handling code here:
        new form_utama().setVisible(true);
        dispose();
    }//GEN-LAST:event_tbkembaliActionPerformed

    private void btbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbatalActionPerformed
        // TODO add your handling code here:
        kosongkan();
        nonaktif();
    }//GEN-LAST:event_btbatalActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        // TODO add your handling code here:
        try {
            stat.executeUpdate("delete from user where "
                + "username='"+user.getText()
                +"'" );
            kosongkan();
            JOptionPane.showMessageDialog(null, "Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "pesan salah : "+e);
        }finally{
            tabel();
        }
    }//GEN-LAST:event_bthapusActionPerformed

    private void btubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btubahActionPerformed
        // TODO add your handling code here:
        try {
            stat.executeUpdate("update user set "
                + "username='"+user.getText()+"',"
                + "nama_user='"+nama.getText()+"',"
                + "password='"+pass.getText()+"',"
                + "level='"+cmhak.getSelectedItem()+"'"

                + " where " + "username='"+user.getText()+"'" );
            JOptionPane.showMessageDialog(rootPane, "Data berhasil Diubah");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }finally{
            tabel();
            kosongkan();
        }
    }//GEN-LAST:event_btubahActionPerformed

    private void btsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsimpanActionPerformed
        // TODO add your handling code here:
        aktif();
        try {
            stat.executeUpdate("insert into user values (NULL,"
                + "'" + nama.getText()+"',"
                + "'" + user.getText()+"',"
                + "'" + pass.getText()+"',"
                + "'" + cmhak.getSelectedItem()+"')");
            JOptionPane.showMessageDialog(null, "Berhasil Menyimpan Data");
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Perintah Salah : "+e);
        }finally{
            tabel();
            kosongkan();
        }
    }//GEN-LAST:event_btsimpanActionPerformed

    private void btcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcariActionPerformed
        // TODO add your handling code here:
        aktif();
        try {
            res=stat.executeQuery("select * from user where "+ "username='" +user.getText()
                +"'" );
            while (res.next())
            {
                user.setText(res.getString("username"));
                nama.setText(res.getString("nama_user"));
                pass.setText(res.getString("password"));
                cmhak.setSelectedItem(res.getString("level"));
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btcariActionPerformed

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
        // TODO add your handling code here:
        aktif();
        kosongkan();
    }//GEN-LAST:event_bttambahActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_userKeyPressed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        if (i == -1){
            return;
        }
        String username = (String) jTable1.getValueAt(i,0);
        user.setText(username);
        String nama_user = (String) jTable1.getValueAt(i,1);
        nama.setText(nama_user);
        String password = (String) jTable1.getValueAt(i,2);
        pass.setText(password);
        String level = (String) jTable1.getValueAt(i,3);
        cmhak.setSelectedItem(level);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbatal;
    private javax.swing.JButton btcari;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btsimpan;
    private javax.swing.JButton bttambah;
    private javax.swing.JButton btubah;
    private javax.swing.JComboBox<String> cmhak;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField pass;
    private javax.swing.JButton tbkembali;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
