/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundry;

/**
 *
 * @author Aas
 */
//import laundry.form_user1;
public class form_utama extends javax.swing.JFrame {

    private String akses;
    private String nama;
    
    /**
     * Creates new form form_utama
     */
   
    public form_utama() {
        initComponents();
        this.setLocationRelativeTo(null);
        jMenu1.setVisible(false);
        jMenu4.setVisible(false);
    }
    
    public void setAkses(String akses) {
        labelAkses.setText("test");
    }
    public String getAkses(){
        return akses;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAkses = new javax.swing.JLabel();
        backgroud = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        user = new javax.swing.JMenuItem();
        pelanggan = new javax.swing.JMenuItem();
        cucian = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        penerimaancucian = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        laporantransaksi = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelAkses.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelAkses.setText("akses");
        getContentPane().add(labelAkses, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 80, 30));

        backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/8.png"))); // NOI18N
        getContentPane().add(backgroud, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("Master");

        user.setText("User");
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jMenu1.add(user);

        pelanggan.setText("Pelanggan");
        pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelangganActionPerformed(evt);
            }
        });
        jMenu1.add(pelanggan);

        cucian.setText("Cucian");
        cucian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cucianActionPerformed(evt);
            }
        });
        jMenu1.add(cucian);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Transaksi");

        penerimaancucian.setText("Penerimaaan");
        penerimaancucian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penerimaancucianActionPerformed(evt);
            }
        });
        jMenu3.add(penerimaancucian);

        transaksi.setText("Pengambilan");
        transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiActionPerformed(evt);
            }
        });
        jMenu3.add(transaksi);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Laporan");

        laporantransaksi.setText("bulan dan berdasarkan tanggal");
        laporantransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporantransaksiActionPerformed(evt);
            }
        });
        jMenu4.add(laporantransaksi);

        jMenuBar1.add(jMenu4);

        exit.setText("Log Out");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Logout");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        exit.add(jMenuItem1);

        jMenuBar1.add(exit);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Login lg = new Login();
        lg.show();
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void laporantransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporantransaksiActionPerformed
        // TODO add your handling code here:
        laporan_transaksi mu = new laporan_transaksi();
        mu.show();
        this.setVisible(false);
    }//GEN-LAST:event_laporantransaksiActionPerformed

    private void transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiActionPerformed
        // TODO add your handling code here
        form_transaksi mu = new form_transaksi();
        mu.show();
        this.setVisible(false);
    }//GEN-LAST:event_transaksiActionPerformed

    private void penerimaancucianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penerimaancucianActionPerformed
        // TODO add your handling code here:
        form_penerimaan_cucian mu = new form_penerimaan_cucian();
        mu.show();
        this.setVisible(false);
    }//GEN-LAST:event_penerimaancucianActionPerformed

    private void cucianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cucianActionPerformed
        // TODO add your handling code here:
        form_cucian mu = new form_cucian();
        mu.show();
        this.setVisible(false);
    }//GEN-LAST:event_cucianActionPerformed

    private void pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelangganActionPerformed
        // TODO add your handling code here:
        form_pelanggan mu = new form_pelanggan();
        mu.show();
        this.setVisible(false);
    }//GEN-LAST:event_pelangganActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
        form_user mu = new form_user();
        mu.show();
        this.setVisible(false);
    }//GEN-LAST:event_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_utama().setVisible(true);
                                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroud;
    private javax.swing.JMenuItem cucian;
    private javax.swing.JMenu exit;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel labelAkses;
    private javax.swing.JMenuItem laporantransaksi;
    private javax.swing.JMenuItem pelanggan;
    private javax.swing.JMenuItem penerimaancucian;
    private javax.swing.JMenuItem transaksi;
    private javax.swing.JMenuItem user;
    // End of variables declaration//GEN-END:variables
}
