package laundry;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aas1
 */
public class liat_penerimaan_cucian extends java.awt.Dialog {

    konek kon = new konek();
    public form_transaksi penerimaan_cucian = null;
    private Object[][] data_penerimaan_cucian = null;
    private String[] label = {"Id Order", "No Order", "Id Pelanggan", "Nama Pelanggan", "tgl_penerimaan", "tgl_pengambilan", "total", "status", "Estimasi Pengerjaan"};

    /**
     * Creates new form liat_penerimaan_cucian
     */
    public liat_penerimaan_cucian(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Form Data Penerimaan Cucian");
        kon.setKoneksi();
        this.setLocationRelativeTo(null);
        BacaTabelTransaksi();
    }

    private void BacaTabelTransaksi() {
        try {
            String sql = "Select *From penerimaan_cucian a join pelanggan b on a.id_pelanggan = b.id_pelanggan order by no_order";
            kon.rs = kon.st.executeQuery(sql);
            ResultSetMetaData m = kon.rs.getMetaData();
            int kolom = m.getColumnCount();
            int baris = 0;
            while (kon.rs.next()) {
                baris = kon.rs.getRow();
            }
            data_penerimaan_cucian = new Object[baris][kolom];
            int x = 0;
            kon.rs.beforeFirst();
            while (kon.rs.next()) {
                data_penerimaan_cucian[x][0] = kon.rs.getString("id_order");
                data_penerimaan_cucian[x][1] = kon.rs.getString("no_order");
                data_penerimaan_cucian[x][2] = kon.rs.getString("id_pelanggan");
                data_penerimaan_cucian[x][3] = kon.rs.getString("nama_pelanggan");
                data_penerimaan_cucian[x][4] = kon.rs.getString("tgl_penerimaan");
                data_penerimaan_cucian[x][5] = kon.rs.getString("tgl_pengambilan");
                data_penerimaan_cucian[x][6] = kon.rs.getString("total");
                data_penerimaan_cucian[x][7] = kon.rs.getString("status_cucian");
                data_penerimaan_cucian[x][8] = kon.rs.getString("estimasi_pengerjaan");
                x++;
            }
            tabel_penerimaan_cucian.setModel(new DefaultTableModel(data_penerimaan_cucian, label));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void BacaTabelTransaksi2() {
        try {
            String sql = "Select *From penerimaan_cucian a join pelanggan b on a.id_pelanggan = b.id_pelanggan "
                    + "where no_order like'%" + tcari.getText() + "%' or nama_pelanggan like'%" + tcari.getText() + "%'";
            kon.rs = kon.st.executeQuery(sql);
            ResultSetMetaData m = kon.rs.getMetaData();
            int kolom = m.getColumnCount();
            int baris = 0;
            while (kon.rs.next()) {
                baris = kon.rs.getRow();
            }
            data_penerimaan_cucian = new Object[baris][kolom];
            int x = 0;
            kon.rs.beforeFirst();
            while (kon.rs.next()) {
                data_penerimaan_cucian[x][0] = kon.rs.getString("id_order");
                data_penerimaan_cucian[x][1] = kon.rs.getString("no_order");
                data_penerimaan_cucian[x][2] = kon.rs.getString("id_pelanggan");
                data_penerimaan_cucian[x][3] = kon.rs.getString("nama_pelanggan");
                data_penerimaan_cucian[x][4] = kon.rs.getString("tgl_penerimaan");
                data_penerimaan_cucian[x][5] = kon.rs.getString("tgl_pengambilan");
                data_penerimaan_cucian[x][6] = kon.rs.getString("total");
                data_penerimaan_cucian[x][7] = kon.rs.getString("status_cucian");
                data_penerimaan_cucian[x][8] = kon.rs.getString("estimasi_pengerjaan");
                x++;
            }
            tabel_penerimaan_cucian.setModel(new DefaultTableModel(data_penerimaan_cucian, label));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_penerimaan_cucian = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tcari = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(144, 190, 171));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Nyala", 1, 24)); // NOI18N
        jLabel1.setText("Data Penerimaan Cucian");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tabel Penerimaan Cucian"));

        tabel_penerimaan_cucian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_penerimaan_cucian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_penerimaan_cucianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_penerimaan_cucian);

        jLabel2.setText("Cari Penerimaan Cucian :");

        tcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tcariKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void tabel_penerimaan_cucianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_penerimaan_cucianMouseClicked
        // TODO add your handling code here:

        int tabel_penerimaan = tabel_penerimaan_cucian.getSelectedRow();

        String item1;

        if (tabel_penerimaan_cucian.getValueAt(tabel_penerimaan, 5) != null) {
            item1 = tabel_penerimaan_cucian.getValueAt(tabel_penerimaan, 5).toString();
        } else {
            item1 = null;
        }

        penerimaan_cucian.idOrder = tabel_penerimaan_cucian.getValueAt(tabel_penerimaan, 0).toString();
        penerimaan_cucian.noOrder = tabel_penerimaan_cucian.getValueAt(tabel_penerimaan, 1).toString();
        penerimaan_cucian.idPelanggan = tabel_penerimaan_cucian.getValueAt(tabel_penerimaan, 2).toString();
        penerimaan_cucian.namaPelanggan = tabel_penerimaan_cucian.getValueAt(tabel_penerimaan, 3).toString();
        penerimaan_cucian.tanggalPenerimaan = tabel_penerimaan_cucian.getValueAt(tabel_penerimaan, 4).toString();
        penerimaan_cucian.tanggalPengambilan = item1;
        
        penerimaan_cucian.estimasiPengerjaan = tabel_penerimaan_cucian.getValueAt(tabel_penerimaan, 4).toString();
        
        penerimaan_cucian.total = tabel_penerimaan_cucian.getValueAt(tabel_penerimaan, 6).toString();

//        penerimaan_cucian.total = tabel_penerimaan_cucian.getValueAt(tabel_penerimaan, 6).toString();
//        penerimaan_cucian.status = tabel_penerimaan_cucian.getValueAt(tabel_penerimaan, 7).toString();
//        penerimaan_cucian.estimasiPengerjaan = tabel_penerimaan_cucian.getValueAt(tabel_penerimaan, 8).toString();
        this.dispose();
    }//GEN-LAST:event_tabel_penerimaan_cucianMouseClicked

    private void tcariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcariKeyTyped
        // TODO add your handling code here:
        BacaTabelTransaksi2();
    }//GEN-LAST:event_tcariKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                liat_penerimaan_cucian dialog = new liat_penerimaan_cucian(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_penerimaan_cucian;
    private javax.swing.JTextField tcari;
    // End of variables declaration//GEN-END:variables
}
